blog/blog/urls.py
from django.conf import settings
from django.views.static import serve  # 处理静态文件
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from myblog import views
from django.conf.urls.static import static

urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),  # django-jet 路由
    path('admin/', admin.site.urls),    # 后台管理系统
    path('', views.Index.as_view(), name='index'),   # 首页
    path('blog/', include(('myblog.urls', 'myblog'), namespace='myblog')),  # 定义二级路由
    # url(r'^admin/', admin.site.urls),
    # url(r"test/",views.test),
    # http://127.0.0.1:8000/v1/user
    # url(r"^v1/users", include("user.urls")),
    # http://127.0.0.1:8000/v1/tokens
    # url(r"^v1/tokens", include("wtoken.urls")),
    #   http://127.0.0.1:8000/v1/topic
    # url(r"^v1/topics", include("topic.urls")),
    # http://127.0.0.1:8000/v1/topic
    # url(r"^v1/messages", include("message.urls"))
]

#绑定media_url 和 media_root,显性操作
#127.0.0.1:8000/media/ ->  MEDIA_ROOT
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    #  配置静态文件访问处理
    urlpatterns.append(url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}))
    urlpatterns.append(url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}))

# 全局页面配置
handler403 = 'myblog.views.page_not_look'
handler404 = 'myblog.views.page_not_found'
handler500 = 'myblog.views.page_error'

blog/myblog/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from django.conf.urls import url

__author__ = "qiu"
__date__ = "2019-11-04 19:45"

from django.urls import path
from . import views
from .views import *

urlpatterns = [
    path('index/', Index.as_view(), name='index'),  # 首页
    path('about/', About.as_view(), name='about'),  # 关于
    path('archive/', Archive.as_view(), name='archive'),  # 归档
    path('link/', Link.as_view(), name='link'),   # 链接
    path('message', Message.as_view(), name='message'),   # 留言
    path('article/<int:pk>/', Articles.as_view(), name='article'),   # 文章列表
    path('get_comment/', GetComment, name='get_comment'),  # 留言信息回推接收
    path('detail/<int:pk>/', Detail.as_view(), name='detail'),   # 文章详情
    path('search/', Search.as_view(), name='search'),     # 全局搜索处理
    path('tag/<int:id>/', Tagcloud.as_view(), name='tag'),   # 标签云
    path('login/',Login.as_view(),name='login'), #登录界面
    path('register/', Register.as_view(), name='register'),  # 登录界面
    # url("^login$",views.login_view,name="login_view"),
    url('^check_status/$', views.check_status, name='check_status'), #检测状态
    url('^send_sms_codes/$',views.send_sms_codes,name="send_sms_codes") #发送验证码
]

blog/templates/archive.html
{% extends "base.html" %}
{% load custom_filter %}

{% block title %}
    <title>博客归档</title>
{% endblock %}

{% block css %}
    <link href="/static/archives/style.css" rel="stylesheet"/>
{% endblock %}

{% block content %}
    <section class="mysection main" style="animation: fuxiasuo 0.8s;">
        <ul class="timeline">
            {% for article in article_list %}
                <li class="event">
                    <input type="radio" name="tl-group" {% if forloop.counter0 == 0 %} checked {% endif %}/>
                    <label></label>
                    <div class="thumb"><span>{{ article.edit_time }}</span></div>
                    <div class="content-perspective">
                        <div class="content">
                            <div class="content-inner">
                                <h3><a href="{% url "myblog:detail" article.id%}">{{ article.title }}</a></h3>
                                <p>{{ article.digest }}</p>
                            </div>
                        </div>
                    </div>
                </li>
            {% endfor %}
        </ul>
    </section>
{% endblock %}

blog/templates/articles.html
{% extends "base.html" %}
{% load custom_filter %}

{% block title %}
    <title>博客列表</title>
{% endblock %}

{% block content %}
    {% paginate article_list 8 %}
    {% if article_list %}
    <section class="mysection">
        <h4 class="index-title">
            <a href="{% url "myblog:article" 0 %}"><i class="el-th-list"></i>{% if category %}列表{% else %} 全部 {% endif %} &nbsp;&nbsp;> &nbsp;&nbsp;</a>
            <span class="orange-text">{{ category }}</span>
            <span style="float:right;margin-right:10px;">共有文章:<a class="orange-text"> {{ count }} </a>篇</span>
        </h4>
        <div class="arclist">
            <!--列表开始-->
            <ul>
                {% for article in article_list %}
                    <li {% if article.read_nums > 500 %}id="tuijian"{% elif article.read_nums > 100 %} id="Hot" {% endif %}>
                    <div class="arcimg">

                        <img src="{{ MEDIA_URL }}{{ article.image }}"
                             alt="{{ article.title }}" title="{{ article.title }}"/>
                    </div>
                    <div class="arc-right">
                        <h4 class="blue-text"><a href="{% url "blog:detail" article.id %}" title="{{ article.title }}">{{ article.title }}</a></h4>
                        <p>{{ article.digest }}</p>
                        <ul>
                            <li><a title="{{ article.author }} {{ article.edit_time }} 发表 "><i class="el-time"></i> {{ article.edit_time }}</a></li>
                            <li><a href="#" title="作者： {{ article.author }}"><i class="el-user"></i>{{ article.author }}</a></li>
                            <li><a href="#" title="已有 {{ article.conment_nums }} 条评论"><i class="el-comment"></i>{{ article.conment_nums }}</a>
                            </li>
                            <li><a title="已有 {{ article.read_nums }} 次浏览"><i class="el-eye-open"></i>{{ article.read_nums }}</a></li>
                            <li class="mob-hidden">
                                <i class="el-tag"></i>
                                <a href="#">{{ article.tag.values| getTag }}</a>&nbsp;
                            </li>
                            <li><a href="{% url "myblog:article" article.category.id %}" title="查看分类"><i class="el-th-list"></i>{{ article.category.name }}</a></li>
                        </ul>
                    </div>
                </li>
                {% endfor %}
            </ul>
            <!--列表结束-->
        </div>
        <!--分页-->

        <div class="pagination">
            <div class="list-page">
                <ul class="post-data">
                    <li><a>第 {{ current_page }} - {{ last_page }} 页</a> <a>共 {{ count }} 条</a></li>
                </ul>
            </div>
            <ul>
                <li {% if current_page == 1 %}class="active"{% endif %}><a href="?page=1">首页</a></li>
                <li {% if current_page >= 2 %} {% else %}class="active"{% endif %}><a href="?page={{ current_page|add:-1 }}">上一页</a></li>
                <li {% if current_page < last_page %} {% else %}class="active"{% endif %}><a href="?page={{ current_page|add:1 }}">下一页</a></li>
                <li {% if current_page == last_page %}class="active"{% endif %}><a href="?page={{ last_page }}">尾页</a></li>
            </ul>
        </div>

    </section>
    {% else %}
    <section class="mysection" style="animation: fuxiasuo 0.8s;">暂时没有任何文章。</section>
    {% endif %}

{% endblock %}

blog/templates/footer.html
<footer>
    <!--底部导航-->
    <div class="foot-nav">
        <div class="copy-right"><span>CopyRight &#169; 2020-2021 博客 &#160;&#160;&#160;     Design by xxx</span></div>
        <div class="license bottom-nav">
            <a href="http://www.miitbeian.gov.cn">@2017 spiderpy.cn 	京ICP备17012574号-1</a></span>
        </div>
    </div>
    <div id="toTop">Back to Top</div>
    <script>
    </script>
</footer>

blog/templates/header.html
<style>
    .myheader{
        background-image: url("/static/images/bgimg/page_photo.png");
        width: 100%;
    }
    .reg_log{
        {#background-color: #0a68a3;#}
        position: relative;
        margin-top: 25px;
        font-size: 16px;
        color:#ff6700;
    }
    .myheader .logo_btn:hover{
        font-size: 20px;
        color: #000;
        cursor:pointer;
    }
    .exit_btn{
        {#position: relative;#}
        float: left;
        {#background-color: red;#}
        margin-top: 25px;
        margin-left: 0;
        width:4%;
        text-align: center;
        color: #ff6700;
    }

    .exit_btn:hover{
        color:#fff;
        font-size:20px;
        cursor: pointer;
    }
    .exit_btn img{
        float: left;
        width:100%;
        height: 45px;
        margin-left: 10px;
    }
</style>

<script src="/static/js/jquery.2.1.4.min.js"></script>
<script src="/static/js/my.js"></script>
<header class="myheader">
    <div class="exit_btn" id="exit_btn"><a href=""><img src="/static/images/h.gif" alt=""></a></div>
    <div class="top">
        <!--头像左边部分，logo-->
        <div class="top-left">
            <div class="reg_log">  <!--reg_log-->
              <a class="logo_btn" id="login_btn" href={% url "myblog:login" %}>登录</a>
              <a class="logo_btn" id="register_btn" href={% url "myblog:register" %}>注册</a>
            </div>
            {#<div class="logo"><a href="/"><img src="/static/images/qiu01.png"/></a></div>#}
            {#<div class="logo"><a href="#"><img src="/static/images/logo.png"/></a></div>#}

            <!--滚动消息-->
            <div class="web-xiaoxi">
                <i class="el-speaker"></i>
                <ul id="mulitline" class="mulitline">
                    <li>全功能博客系统</li>
                    <li>Stay hungry,Stay foolish</li>
                    <!--完美自适应手机-->
                    <li>Keep looking,Don't sate</li>
                </ul>
            </div>
            <!--END 消息 -->

            <!--手机菜单按钮-->
            <div class="mobile-nav"><i class="el-lines"></i><i class="el-remove"></i></div>
        </div>

        <!--电脑导航开始-->
        <nav class="mynav">
            <ul class="orange-text">
                <li class=""><a href="{% url "myblog:index" %}">首页</a></li>
                <li><a href="{% url "myblog:about" %}">关于</a></li>
                <li><a href="{% url "myblog:article" 0 %}">博客</a></li>
                <li class='drop'>
                    <a href="JavaScript:;">分类<i class='el-chevron-down'></i></a>
                    <div class="drop-nav orange-text ">
                        <ul>
                            {% for category in category_list %}
                                <li><a href="{% url "myblog:article" category.id %}">{{ category.name }}</a></li>
                            {% endfor %}
                        </ul>
                    </div>
                </li>
                <li><a href="{% url "myblog:archive" %}">归档</a></li>
                <li><a href="{% url "myblog:link" %}">链接</a></li>
                <li><a href="{% url "myblog:message" %}">留言</a></li>
            </ul>
        </nav>

        <!--这里是手机导航-->
        <div class="mob-menu">
            <!--手机顶部搜索-->
            <div class="search ">
                <form action="{% url "myblog:search" %}" method="get">
                    <div class="search-index">
                        <input name="name" type="text" placeholder="请输入关键字" onfocus="this.placeholder=''"
                               onblur="this.placeholder='请输入关键字'"/>
                        <i class="el-search"><input value=" " type="submit"/></i>
                    </div>
                </form>
            </div>
            <!--手机下拉菜单-->
            <ul>
                <li><a href="{% url "myblog:index" %}">首页</a></li>
                <li><a href="{% url "myblog:about" %}">关于</a></li>
                <li><a href="{% url "myblog:article" pk=0 %}">博客</a></li>
                <li class='mob-drop'>
                    <a href="javascrip:;">分类</a>
                    <ul class="mob-dropmenu">
                        {% for category in category_list %}
                            <li><a href="{% url "myblog:article" category.id %}">{{ category.name }}</a></li>
                        {% endfor %}
                    </ul>
                </li>
                <li><a href="{% url "myblog:archive" %}">归档</a></li>
                <li><a href="{% url "myblog:link" %}">链接</a></li>
                <li><a href="{% url "myblog:message" %}">留言</a></li>
            </ul>
        </div>
    </div>
    <!--换肤--->
    <script src="/static/js/skin.js"></script>
    <div class="select-skin">
        <div class="skin-btn">
            <a href="javascript:void(0);" class="skin-btn-open">换<br>肤</a>
        </div>

        <div class="skin-content">
            <h1>选择风格<span class="skin-close">关闭</span></h1>
            <div class="skin-content-list">
                <div class="skin-list"><a href="#" onclick="setActiveStyleSheet('qingxin'); return false;" class="btn1">清新</a>
                </div>
                <div class="skin-list"><a href="#" onclick="setActiveStyleSheet('jianyue'); return false;" class="btn2">简约</a>
                </div>
                <div class="skin-list"><a href="#" onclick="setActiveStyleSheet('qingshuang'); return false;"
                                          class="btn3">清爽</a></div>
            </div>
        </div>
    </div>
</header>

{#script,检查登录+文字滚动+点击时间#}
<script>
    //检查登录状态
    function check_login(){
        var token = window.localStorage.getItem('qiublog_token')
        var username =  window.localStorage.getItem('qiublog_user')
        var post_data = {
        'username':username,
        'token':token
        }
        $.ajax({
        // 请求方式
        type:"post",
        // contentType
        contentType:"application/json",
        // dataType
        dataType:"json",
        // url
        url:"http://127.0.0.1:8000/blog/check_status/",
        beforeSend: function(request) {
           request.setRequestHeader("Authorization", token);
        },
        //url:"http://127.0.0.1:8000/test/",
        // 把JS的对象或数组序列化一个json 字符串
        data:JSON.stringify(post_data),
        // result 为请求的返回结果对象
        success:function (result) {
            if (200 == result.code){
                html = ""
                html += "<img style='float:left;border-radius:50%;text-align:center;margin-top:-5.5px;height:30px;width:20px' src='/static/images/lufei.gif' />"
                html += "&nbsp;追风者"
                html += result.data.username
                $(".reg_log").css("fontSize","20px")
                $(".reg_log").css("color","#000")
                $(".reg_log").html(html)
                $(".exit_btn").text("退出")
                $(".exit_btn").display="block"

            }else{
                {#html = ""#}
                {#html += "<a class=\"logo_btn\" id=\"login_btn\" href={% url 'myblog:login' %}>登录</a>\n"#}
                {#html += "<a class=\"logo_btn\" id=\"register_btn\" href={% url 'myblog:register' %}>注册</a>"#}
                {#$(".reg_log").html(html)#}
                console.log(result.error)
            }}
        });
        }
    //文字滚动
    function text_scroll(){
            var _wrap = $('#mulitline');//定义滚动区域
            var _interval = 3000;//定义滚动间隙时间
            var _moving;//需要清除的动画
            _wrap.hover(function () {
                clearInterval(_moving);//当鼠标在滚动区域中时,停止滚动
            }, function () {
                _moving = setInterval(function () {
                    var _field = _wrap.find('li:first');//此变量不可放置于函数起始处，li:first取值是变化的
                    var _h = _field.height();//取得每次滚动高度
                    _field.animate({ marginTop: -_h + 'px' }, 500, function () {//通过取负margin值，隐藏第一行
                        _field.css('marginTop', 0).appendTo(_wrap);//隐藏后，将该行的margin值置零，并插入到最后，实现无缝滚动
                    })
                }, _interval)//滚动间隔时间取决于_interval
            }).trigger('mouseleave');//函数载入时，模拟执行mouseleave，即自动滚动
            if ($("#mulitline li").length <= 1)//小于等于1条时，不滚动
            {
                clearInterval(_moving);
            }
        }
    $(function () {
        $("#login_btn").click(function () {
            window.location.href = "login.html"
        })
        $("#register_btn").click(function () {
            window.location.href = "register.html"
        })
        $("#exit_btn").click(function () {
            localStorage.removeItem('qiublog_token');
            console.log(localStorage.getItem('qiu_blogtoken'));
            window.location.reload()
        })
        check_login()
        text_scroll()
    });
</script>

blog/templates/link.html
{% extends "base.html" %}

{% block title %}
    <title>链接 </title>
{% endblock %}

{% block content %}
    <section class="mysection" style="animation: fuxiasuo 0.8s;">页面建设中。。。。</section>

{% endblock %}

blog/templates/right.html
<aside class="myaside">
    <!--关注我-->
    <div class="focus-me bg-color animation-div">
        <h4 class="index-title"><i class="el-heart"></i>关注我
            <small>Focus Me</small>
        </h4>
        <div class="xiangguan">

            <div><a class="benbo" href="#" target="_blank"><i
                    class="el-download-alt"></i></a><span>更多资源</span></div>
            <div><a class="taobao"
                    href="https://blog.csdn.net/sinat_36618660"
                    target="_blank"><i class="el-blogger"></i></a><span>我的CSDN</span></div>
            <div><a class="side-fx"><i class="el-share-alt"></i></a><span>分享本博</span></div>
            <div><a class="mail-btn" href="javascript:;"><i class="el-envelope"></i></a><span>订阅我</span></div>
        </div>

        <div class="mail-dy">
            <form action="#">
                <input type="hidden" name="t" value="qf_booked_feedback"/>
                <input type="hidden" name="id" value="b2b151b4bc010575c083e18e227ae907aac82bc47e84d3e0"/>
                <span>订阅</span>
                <input name="to" type="text" placeholder="输入邮箱点击订阅吧" onfocus="this.placeholder=''"
                       onblur="this.placeholder='输入邮箱点击订阅吧(暂无)'"/>
                <i class="el-envelope"><input value=" " type="submit"/></i>
            </form>
            <i class="el-remove fx-close"></i>
        </div>

        <div class="bd-fx side-bdfx ">
            <i class="el-remove fx-close"></i>
            <ul class="bdsharebuttonbox">
                <li><a href="#" class="bds_weixin" data-cmd="weixin" title="分享到微信"></a></li>
                <li><a href="#" class="bds_tsina" data-cmd="tsina" title="分享到新浪微博"></a></li>
                <li><a href="#" class="bds_qzone" data-cmd="qzone" title="分享到QQ空间"></a></li>
                <li><a href="#" class="bds_tieba" data-cmd="tieba" title="分享到百度贴吧"></a></li>
            </ul>
            <script>window._bd_share_config = {
                "common": {
                    "bdSnsKey": {},
                    "bdText": "",
                    "bdMini": "2",
                    "bdMiniList": false,
                    "bdPic": "",
                    "bdStyle": "1",
                    "bdSize": "32"
                }, "share": {}
            };
            with (document)0[(getElementsByTagName('head')[0] || body).appendChild(createElement('script')).src = 'http://bdimg.share.baidu.com/static/api/js/share.js?v=89860593.js?cdnversion=' + ~(-new Date() / 36e5)];</script>
        </div>
    </div>
    <!--最新更新-->

    <div class="clos-new bg-color animation-div">
        <h4 class="index-title"><i class="el-bulb"></i>最新资讯
            <small>Latest News</small>
        </h4>
        <ul>
            <li><i class="el-cloud"></i>
                <iframe id="tianqi" scrolling="no" frameborder="0" allowtransparency="true"
                        src="http://i.tianqi.com/index.php?c=code&a=getcode&id=34&h=25&w=280"></iframe>
            </li>

            <li><i class="el-calendar"></i>历史今天：
                <iframe src="http://www.todayonhistory.com/code/6.html?w=250&h=20&bky=dotted&bks=0&fs=14&fc=#565656&hg=14&ie=0&xhx=none&sd=300&px=3&len=0&sk=1&n=0"
                        width="250" height="15" scrolling="no" frameborder="0" allowtransparency="true"></iframe>
            </li>
        </ul>
    </div>
    <!--搜索-->
    <div class="search animation-div">
        <form action="{% url "myblog:search" %}" method="get">
            <div class="search-index">
                <input name="key" type="text" placeholder="请输入关键字" onfocus="this.placeholder=''"
                       onblur="this.placeholder='请输入关键字'"/>
                <i class="el-search"><input value=" " type="submit"/></i>
            </div>
        </form>
    </div>

    <!--文章排行tab-->
    <div class="mytab bg-color animation-div">
        <div class="tab-btn"><a class="hd-btn tab-active" href="javascript:;"><i class="el-comment-alt"></i>最新评论</a><a
                class="ph-btn" href="javascript:;"><i class="el-signal"></i>文章排行</a></div>
        <ul class="hudong-ul">
            <!--=======查询相册=============-->
            {% for comment in comment_list %}
                <li>
                    <div class="sd-name">
                        <span><i class="el-book"></i>{{ comment.title }}</span>
                        <a class="blue-text" href="{{ comment.url }}" title="{{ comment.comment }}">{{ comment.comment }}</a>
                        <span style="text-align: right">— &nbsp;<i class="el-user"></i>{{ comment.user }}</span>
                    </div>
                </li>
            {% endfor %}


        </ul>
        <!--文章排行-->
        <ul class="paihang-ul">
            {% for article in article_rank %}
                <li><span></span><a href="{% url "myblog:detail" article.id %}"
                                    title="{{ article.title }}">{{ article.title }}<b><i
                        class="el-eye-open"></i>({{ article.read_nums }})</b></a></li>
            {% endfor %}
        </ul>

    </div>

    <!--标签-->
    <div class="cloud bg-color animation-div">
        <h4 class="index-title"><i class="el-tags"></i>标签云
            <small>Tags Clouds</small>
        </h4>
        <ul id="3dcloud">
            {% for tag in tag_list %}
                <li><a href="{% url "myblog:tag" tag.id %}" title="标签：{{ tag.tag_name }} ">{{ tag.tag_name }}</a></li>
            {% endfor %}
        </ul>
    </div>


    <!--友情链接-->
    {% include "blogroll.html" %}
</aside>

blog/templates/search.html
{% extends "base.html" %}

{% block title %}
    <title>搜索:{{ key }}</title>
{% endblock %}

{% load custom_filter %}
{% block content %}
    {% paginate article_list 8 %}
    <section class="mysection">
        <h4 class="index-title">
            <a href="{% url "myblog:article" pk=0 %}"><i class="el-search"></i> 搜索到<b class="lable">{{ key }}</b>相关结果</a>
            <span style="float:right;margin-right:10px;">共:<a class="orange-text"> {{ count }} </a>条</span>
        </h4>
        <div class="arclist">
            <!--列表开始-->
            <ul>
                {% for article in article_list %}
                    <li {% if article.read_nums > 500 %}id="tuijian"{% elif article.read_nums > 100 %} id="Hot" {% endif %}>
                    <div class="arcimg">

                        <img src="{{ MEDIA_URL }}{{ article.image }}"
                             alt="{{ article.title }}" title="{{ article.title }}"/>
                    </div>
                    <div class="arc-right">
                        <h4 class="blue-text"><a href="{% url "blog:detail" article.id %}" title="{{ article.title }}">{{ article.title }}</a></h4>
                        <p>{{ article.digest }}</p>
                        <ul>
                            <li><a title="{{ article.author }} {{ article.edit_time }} 发表 "><i class="el-time"></i> {{ article.edit_time }}</a></li>
                            <li><a href="#" title="作者： {{ article.author }}"><i class="el-user"></i>{{ article.author }}</a></li>
                            <li><a href="#" title="已有 {{ article.conment_nums }} 条评论"><i class="el-comment"></i>{{ article.conment_nums }}</a>
                            </li>
                            <li><a title="已有 {{ article.read_nums }} 次浏览"><i class="el-eye-open"></i>{{ article.read_nums }}</a></li>
                            <li class="mob-hidden">
                                <i class="el-tag"></i>
                                <a href="#">{{ article.tag.values| getTag }}</a>&nbsp;
                            </li>
                            <li><a href="{% url "myblog:article" article.category.id %}" title="查看分类"><i class="el-th-list"></i>{{ article.category.name }}</a></li>
                        </ul>
                    </div>
                </li>
                {% endfor %}
            </ul>
            <!--列表结束-->
        </div>
        <!--分页-->

        <div class="pagination">
            <div class="list-page">
                <ul class="post-data">
                    <li><a>第 {{ current_page }} - {{ last_page }} 页</a> <a>共 {{ count }} 条</a></li>
                </ul>
            </div>
            <ul>

                <li {% if current_page == 1 %}class="active"{% endif %}><a href="?page=1">首页</a></li>
                <li {% if current_page >= 2 %} {% else %}class="active"{% endif %}><a href="?page={{ current_page|add:-1 }}">上一页</a></li>
                <li {% if current_page < last_page %} {% else %}class="active"{% endif %}><a href="?page={{ current_page|add:1 }}">下一页</a></li>
                <li {% if current_page == last_page %}class="active"{% endif %}><a href="?page={{ last_page }}">尾页</a></li>
            </ul>
        </div>

    </section>

{% endblock %}

blog/templates/tag.html
{% extends "base.html" %}
{% load custom_filter %}

{% block title %}
    <title>标签：{{ tag }}</title>
{% endblock %}

{% block content %}
    {% paginate article_list 8 %}
    <section class="mysection">
        <h4 class="index-title">
            <a href="{% url "myblog:article" 0 %}"><i class="el-tag"></i> 标签<b class="lable">{{ tag }}</b></a>
            <span style="float:right;margin-right:10px;">共有:<a class="orange-text"> {{ count }} </a>篇</span>
        </h4>
        <div class="arclist">
            <!--列表开始-->
            <ul>
                {% for article in article_list %}
                    <li {% if article.read_nums > 500 %}id="tuijian"{% elif article.read_nums > 100 %} id="Hot" {% endif %}>
                    <div class="arcimg">

                        <img src="{{ MEDIA_URL }}{{ article.image }}"
                             alt="{{ article.title }}" title="{{ article.title }}"/>
                    </div>
                    <div class="arc-right">
                        <h4 class="blue-text"><a href="{% url "myblog:detail" article.id %}" title="{{ article.title }}">{{ article.title }}</a></h4>
                        <p>{{ article.digest }}</p>
                        <ul>
                            <li><a title="{{ article.author }} {{ article.edit_time }} 发表 "><i class="el-time"></i> {{ article.edit_time }}</a></li>
                            <li><a href="#" title="作者： {{ article.author }}"><i class="el-user"></i>{{ article.author }}</a></li>
                            <li><a href="#" title="已有 {{ article.conment_nums }} 条评论"><i class="el-comment"></i>{{ article.conment_nums }}</a>
                            </li>
                            <li><a title="已有 {{ article.read_nums }} 次浏览"><i class="el-eye-open"></i>{{ article.read_nums }}</a></li>
                            <li class="mob-hidden">
                                <i class="el-tag"></i>
                                <a href="#">{{ article.tag.values| getTag }}</a>&nbsp;
                            </li>
                            <li><a href="{% url "myblog:article" article.category.id %}" title="查看分类"><i class="el-th-list"></i>{{ article.category }}</a></li>
                        </ul>
                    </div>
                </li>
                {% endfor %}
            </ul>
            <!--列表结束-->
        </div>
        <!--分页-->

        <div class="pagination">
            <div class="list-page">
                <ul class="post-data">
                    <li><a>第 {{ current_page }} - {{ last_page }} 页</a> <a>共 {{ count }} 条</a></li>
                </ul>
            </div>
            <ul>

                <li {% if current_page == 1 %}class="active"{% endif %}><a href="?page=1">首页</a></li>
                <li {% if current_page >= 2 %} {% else %}class="active"{% endif %}><a href="?page={{ current_page|add:-1 }}">上一页</a></li>
                <li {% if current_page < last_page %} {% else %}class="active"{% endif %}><a href="?page={{ current_page|add:1 }}">下一页</a></li>
                <li {% if current_page == last_page %}class="active"{% endif %}><a href="?page={{ last_page }}">尾页</a></li>
            </ul>
        </div>

    </section>

{% endblock %}